### ISSUE TITLE
IndexOutBoundException when packing scalar value with ByteArrayPacker

### ISSUE THREAD

**Issue by rafael-aero** [msgpack/msgpack-cli#252]
I'm getting the following exception when trying to serialize an object containing a Dictionary<int,int>, using PackSingleObjectAsync(object):

Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at MsgPack.MessagePackByteArrayPacker.WriteBytes(Byte header, UInt32 value)
   at MsgPack.MessagePackByteArrayPacker.<PackAsyncCore>d__47.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MsgPack.Serialization.DefaultSerializers.System_Int32MessagePackSerializer.<PackToAsyncCore>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MsgPack.Serialization.MessagePackSerializer`1.<PackToAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MsgPack.PackerUnpackerExtensions.<PackDictionaryAsyncCore>d__39`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MsgPack.Serialization.MessagePackSerializer`1.<PackToAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MsgPack.Serialization.PackHelpers.<PackToArrayAsyncCore>d__4`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MsgPack.Serialization.MessagePackSerializer`1.<PackToAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MsgPack.Serialization.MessagePackSerializer`1.<PackSingleObjectAsBytesAsync>d__35.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MsgPack.Serialization.MessagePackSerializer`1.<PackSingleObjectAsync>d__34.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

**Comment by BuairtRi** [comment]
I'm getting a similar error, but with a different StackTrack:

Index was outside the bounds of the array.
   at MsgPack.MessagePackByteArrayPacker.WriteBytes(Byte header, UInt16 value)
   at MsgPack.MessagePackByteArrayPacker.PackCore(Int16 value)
   at MsgPack.Serialization.DefaultSerializers.DateTimeOffsetMessagePackSerializer.PackToCore(Packer packer, DateTimeOffset objectTree)
   at MsgPack.Serialization.MessagePackSerializer`1.PackTo(Packer packer, T objectTree)
   at MsgPack.Serialization.EmittingSerializers.Generated.Row52_Data_Models_Data_VehicleDetailSerializer1.PackValueOfDateAdded(Packer , VehicleDetail )
   at MsgPack.Serialization.PackHelpers.PackToArray[TObject](PackToArrayParameters`1& parameter)
   at MsgPack.Serialization.EmittingSerializers.Generated.Row52_Data_Models_Data_VehicleDetailSerializer1.PackToCore(Packer , VehicleDetail )
   at MsgPack.Serialization.MessagePackSerializer`1.PackTo(Packer packer, T objectTree)
   at MsgPack.PackerUnpackerExtensions.PackCollectionCore[T](Packer source, IEnumerable`1 collection, MessagePackSerializer`1 itemSerializer)
   at MsgPack.Serialization.DefaultSerializers.System_Collections_Generic_List_1MessagePackSerializer`1.PackToCore(Packer packer, List`1 objectTree)
   at MsgPack.Serialization.MessagePackSerializer`1.PackTo(Packer packer, T objectTree)
   at MsgPack.Serialization.MessagePackSerializer`1.PackSingleObjectAsBytes(T objectTree)
   at MsgPack.Serialization.MessagePackSerializer`1.PackSingleObject(T objectTree)
   at MsgPack.Serialization.MessagePackSerializer`1.InternalPackSingleObject(Object objectTree)
   at MsgPack.Serialization.MessagePackSerializer.PackSingleObject(Object objectTree)

**Comment by BuairtRi** [comment]
Rolling back to Nuget 0.8.1 resolved the problem for me, so it looks like a bug with the latest release.

**Comment by yfakariya** [comment]
Thank you for reporting! I will investigate it soon.

**Comment by yfakariya** [comment]
@rafael-aero @BuairtRi 
I failed to reproduce this issue. Could you tell me repro code? It should be caused by specific class layout to serialize.

**Comment by BuairtRi** [comment]
I'm trying to serialize a large .NET List of a simple POCO object:

`[DataContract]
    [Serializable]
    [ExportToTypescript]
    public class VehicleDetail
    {
        [DataMember]
        public long Id { get; set; }

        [DataMember]
        public string VIN { get; set; }

        [DataMember]
        public int Year { get; set; }

        [DataMember]
        public int? ModelId { get; set; }

        [DataMember]
        public string Model { get; set; }

        [DataMember]
        public int? MakeId { get; set; }

        [DataMember]
        public string Make { get; set; }

        [DataMember]
        public long LocationId { get; set; }

        [DataMember]
        public string LocationName { get; set; }

        [DataMember]
        public string City { get; set; }

        [DataMember]
        public string State { get; set; }

        [DataMember]
        public string Zip { get; set; }

        [DataMember]
        public string Row { get; set; }

        [DataMember]
        public DateTimeOffset DateAdded { get; set; }

        [DataMember]
        public string BarCodeNumber { get; set; }

        [DataMember]
        public bool HasImage { get; set; }

        [DataMember]
        public string Engine { get; set; }

        [DataMember]
        public string Transmission { get; set; }

        [DataMember]
        public string Trim { get; set; }

        [DataMember]
        public string AccountName { get; set; }

        [DataMember]
        public string Color { get; set; }

        [DataMember]
        public bool IsActive { get; set; }

        [DataMember]
        public bool AllowPullers { get; set; }

        [DataMember]
        public string Url { get; set; }
        [DataMember]
        public Guid? Size1 { get; set; }
        [DataMember]
        public Guid? Size2 { get; set; }
        [DataMember]
        public Guid? Size3 { get; set; }
        [DataMember]
        public Guid? Size4 { get; set; }
        [DataMember]
        public string Extension { get; set; }

        [DataMember]
        public string LocationImageName { get; set; }

        [DataMember]
        public string LocationImageLocation
        {
            get
            {
                if (LocationImageName != null && LocationImageName.Contains("://"))
                    return LocationImageName;

                return "https://cdn.row52.com/cdn/images/accounts/" + LocationImageName;
            }
        }

        [DataMember]
        public string ImageName
        {
            get
            {
                return Size1 == default(Guid)
                           ? "https://cdn.row52.com/cdn/images/imagecomingsoon_600.jpg"
                           : Url + Size1.ToString().ToLower() + Extension;
            }
        }

        [DataMember]
        public string SmallImage
        {
            get
            {
                return Size3 == default(Guid)
                           ? "http://placehold.it/150x113"
                           : Url + Size3.ToString().ToLower() + Extension;
            }
        }

        [DataMember]
        public string LargeImage
        {
            get
            {
                return Size2 == default(Guid)
                           ? "http://placehold.it/150x113"
                           : Url + Size2.ToString().ToLower() + Extension;
            }
        }

        [DataMember]
        public string ThumbNail
        {
            get
            {
                return Size4 == default(Guid)
                           ? "https://cdn.row52.com/cdn/images/imagecomingsoon_150.png"
                           : Url + Size4.ToString().ToLower() + Extension;
            }
        }

        [DataMember]
        public DateTimeOffset ImageDate { get; set; }

        [DataMember]
        public DateTimeOffset? MostRecentComment { get; set; }

        [DataMember]
        public int ImageCount { get; set; }

        [DataMember]
        public string LocationCode { get; set; }

        [DataMember]
        public int CommentCount { get; set; }

        [DataMember]
        public Guid AccountId { get; set; }

        [DataMember]
        public DateTimeOffset CreationDate { get; set; }

        [DataMember]
        public long? FavoriteId { get; set; }

        [DataMember]
        public DateTimeOffset? FavoritedDate { get; set; }

        [DataMember]
        public int PullerCount { get; set; }

        [DataMember]
        public int PartsPullersCount { get; set; }

        [DataMember]
        public int PartsPullersForInYardsCount { get; set; }
    }`

**Comment by yfakariya** [comment]
@BuairtRi Thank you!

**Comment by yfakariya** [comment]
I found a workaround. You should avoid this issue use `Pack` instead of `PackSingleObject`.

**Comment by yfakariya** [comment]
I've fixed this issue and released 0.9.1 now. Please try it.
