### ISSUE TITLE
The unpacked value is not expected type

### ISSUE THREAD

**Issue by safv12** [msgpack/msgpack-cli#343]
Hi guys!

This is a question more than an issue.

I'm doing some tests with two projects in c#, one as a consumer and the other as a producer. In the producer, I'm sending and event with some properties, and in the consumer, I'm receiving this event, but omitting one property. Both objects are equal except that in the consumer I intentionally omit one property.

I'm getting the next error, is this an expected behavior?

```
System.Runtime.Serialization.SerializationException
  HResult=0x8013150C
  Message=The unpacked value is not expected type. Do not convert System.Byte[] MessagePackObject to MsgPack.MessagePackExtendedTypeObject.
  Source=MsgPack
  StackTrace:
   at MsgPack.Serialization.DefaultSerializers.MessagePackObjectExtensions.DeserializeAsMessagePackExtendedTypeObject(MessagePackObject source)
   at MsgPack.Serialization.DefaultSerializers.TimestampDateTimeMessagePackSerializer.UnpackFromCore(Unpacker unpacker)
   at MsgPack.Serialization.MessagePackSerializer`1.UnpackFrom(Unpacker unpacker)
   at MsgPack.Serialization.UnpackHelpers.UnpackComplexObject[T](Unpacker unpacker, MessagePackSerializer`1 serializer, Int32 unpacked)
   at MsgPack.Serialization.UnpackHelpers.UnpackValueTypeValueCore[TContext,TValue](Unpacker unpacker, TContext context, MessagePackSerializer`1 serializer, Int32 itemsCount, Int32 unpacked, Type targetObjectType, String memberName, Func`4 directRead, Action`2 setter)
   at MsgPack.Serialization.UnpackHelpers.UnpackValueTypeValue[TContext,TValue](UnpackValueTypeValueParameters`2& parameter)
   at MsgPack.Serialization.EmittingSerializers.Generated.Madoff_EventBus_Consumer_AccountEvents_Events_AccountCreatedSerializer1.UnpackValueOfCreatedAt(Unpacker , AccountCreated , Int32 , Int32 )
   at MsgPack.Serialization.UnpackHelpers.UnpackFromArrayCore[TContext,TResult](Unpacker unpacker, TContext unpackingContext, Func`2 factory, IList`1 itemNames, IList`1 operations)
   at MsgPack.Serialization.UnpackHelpers.UnpackFromArray[TContext,TResult](UnpackFromArrayParameters`2& parameter)
   at MsgPack.Serialization.UnpackHelpers.UnpackFromArray[TContext,TResult](Unpacker unpacker, TContext context, Func`2 factory, IList`1 itemNames, IList`1 operations)
   at MsgPack.Serialization.EmittingSerializers.Generated.Madoff_EventBus_Consumer_AccountEvents_Events_AccountCreatedSerializer1.UnpackFromCore(Unpacker )
   at MsgPack.Serialization.MessagePackSerializer`1.UnpackFrom(Unpacker unpacker)
   at MsgPack.Serialization.MessagePackSerializer`1.InternalUnpackFrom(Unpacker unpacker)
   at MsgPack.Serialization.MessagePackSerializer.UnpackFrom(Unpacker unpacker)
   at MsgPack.Serialization.MessagePackSerializerExtensions.Unpack(MessagePackSerializer source, Stream stream)
   at MyTestProject.Serialization.MessagePack.MessagePackDeserializer.Deserialize(Type targetType, Byte[] data)
   at MyTestProject.Kafka.Consumer.AspNetCore.HostedServices.EventBusHostedService.<NotifySubscriberAsync>d__9.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at MyTestProject.Kafka.Consumer.AspNetCore.HostedServices.EventBusHostedService.<>c__DisplayClass8_0.<<OnMessageReceivedAsync>b__0>d.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at MyTestProject.Kafka.Consumer.AspNetCore.HostedServices.EventBusHostedService.<OnMessageReceivedAsync>d__8.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at MyTestProject.Kafka.Consumer.AspNetCore.HostedServices.EventBusHostedService.<>c__DisplayClass7_0.<<ExecuteAsync>b__1>d.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

Inner Exception 1:
InvalidOperationException: Do not convert System.Byte[] MessagePackObject to MsgPack.MessagePackExtendedTypeObject.
```

Regards!

**Comment by yfakariya** [comment]
By default, msgpack for cli serializes object as array instead of map (dictionary). In this case, you will face error because msgpack cannot know which property is omitted. To tell the serializer generator to skip some properties from serialized binary, you need to qualify receiver side type with `[MessageMember]` specifying integer `Id` property. Note that msgpack for cli serializes members in lexical order instead of declaring order by default. 
Let's assume a producer side type definition:
```C#
// In producer project
public class EventData
{
    public string MessageId { get; set; } // Id = 1, implicitly
    public Timestamp Timestamp { get; set; } // Id = 2, implicitly
    public byte[] Body { get; set; } // Id = 0, implicitly
}
```

If you want to have the `EventData` without `MessageId` property, you need to declare consumer side type as following:

```C#
// In consumer project
public class EventData
{
    [MessagePackMember(2)]
    public Timestamp Timestamp { get; set; }
    [MessagePackMember(0)]
    public byte[] Body { get; set; }
}
```

**Comment by safv12** [comment]
Got it! Thank you @yfakariya
