### ISSUE TITLE
Do not convert System.Boolean (binary:0x0) MessagePackObject to System.Int64.

### ISSUE THREAD

**Issue by pbattar** [msgpack/msgpack-cli#51]
We get following error while unpacking packed message to an object.
This error is not noticed on local development environment (windows 7) but occurs in the server environment. (server 2008).

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Runtime.Serialization.SerializationException: The unpacked value is not expected type. Do not convert System.Boolean (binary:0x0) MessagePackObject to System.Int64. ---> System.InvalidOperationException: Do not convert System.Boolean (binary:0x0) MessagePackObject to System.Int64.
   at MsgPack.MessagePackObject.ThrowInvalidTypeAs[T](MessagePackObject instance)
   at MsgPack.MessagePackObject.AsInt64()
   at MsgPack.Serialization.DefaultSerializers.System_DateTimeMessagePackSerializer.UnpackFromCore(Unpacker unpacker)
   --- End of inner exception stack trace ---
   at MsgPack.Serialization.DefaultSerializers.System_DateTimeMessagePackSerializer.UnpackFromCore(Unpacker unpacker)
   at MsgPack.Serialization.DefaultSerializers.NullableMessagePackSerializer`1.UnpackFromCore(Unpacker unpacker)
   at MsgPack.Serialization.MessagePackSerializer`1.UnpackFrom(Unpacker unpacker)

**Comment by yfakariya** [comment]
Close because no answer about 6 months.
It is welcome to reopen this issue if you think that this issue should not be closed.

**Comment by ibaig** [comment]
thank you @yfakariya you saved me some time. I was having a similar error because of mismatch in fields between the service and the consumer when using application/x-msgpack where as application/json would still deserialize. Why does the contract has to be an exact match though ?

**Comment by yfakariya** [comment]
@ibaig It may be occurred by msgpack for cli's 'lexical ordering' of array fields. Could you try to qualify your (de)serializing types' fields with `[MessagePackMember(<order>)]`?
